// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvpNqAAO-zfGzhq8vAKgrzbjFKbAAlIU',
    appId: '1:708429443809:web:282623c3f3f5746d713da0',
    messagingSenderId: '708429443809',
    projectId: 'eduv-210b5',
    authDomain: 'eduv-210b5.firebaseapp.com',
    storageBucket: 'eduv-210b5.appspot.com',
    measurementId: 'G-PHTCFB1ZW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvkpzHir259meVvem8s2XaM2RuwxTivug',
    appId: '1:708429443809:android:eef571c7949c8116713da0',
    messagingSenderId: '708429443809',
    projectId: 'eduv-210b5',
    storageBucket: 'eduv-210b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7BEh-gRO9C6ldxCObVqLJ112mGFZX6iQ',
    appId: '1:708429443809:ios:d38aa774ee419d36713da0',
    messagingSenderId: '708429443809',
    projectId: 'eduv-210b5',
    storageBucket: 'eduv-210b5.appspot.com',
    iosClientId: '708429443809-msl08kj0c1j6847p1be34lrpnr3vceum.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7BEh-gRO9C6ldxCObVqLJ112mGFZX6iQ',
    appId: '1:708429443809:ios:d38aa774ee419d36713da0',
    messagingSenderId: '708429443809',
    projectId: 'eduv-210b5',
    storageBucket: 'eduv-210b5.appspot.com',
    iosClientId: '708429443809-msl08kj0c1j6847p1be34lrpnr3vceum.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBvpNqAAO-zfGzhq8vAKgrzbjFKbAAlIU',
    appId: '1:708429443809:web:7f8ade0532661518713da0',
    messagingSenderId: '708429443809',
    projectId: 'eduv-210b5',
    authDomain: 'eduv-210b5.firebaseapp.com',
    storageBucket: 'eduv-210b5.appspot.com',
    measurementId: 'G-XSB57P3HEK',
  );

}